#!/usr/bin/env python3
"""
Generate test data header for test_four_core_48event.c.

This script imports the canonical TASK_SEQUENCE from the Tier 4.22x bridge
and emits a C header with the schedule entries + expected slot values so
the C test can inject deterministic replies.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

from experiments.tier4_22x_compact_v2_bridge_decoupled_smoke import (
    TASK_SEQUENCE,
    FP_ONE,
    FP_SHIFT,
)


def fp_from_float(x: float) -> int:
    return int(round(x * FP_ONE))


def main():
    out_path = Path(__file__).parent / "test_four_core_48event_data.h"

    lines = []
    lines.append("/* Auto-generated by generate_48event_data.py — do not edit manually */")
    lines.append("#ifndef TEST_FOUR_CORE_48EVENT_DATA_H")
    lines.append("#define TEST_FOUR_CORE_48EVENT_DATA_H")
    lines.append("")
    lines.append(f"#define NUM_EVENTS {len(TASK_SEQUENCE)}")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint32_t timestep;")
    lines.append("    uint32_t context_key;")
    lines.append("    uint32_t route_key;")
    lines.append("    uint32_t memory_key;")
    lines.append("    int32_t  context_value;")
    lines.append("    int32_t  route_value;")
    lines.append("    int32_t  memory_value;")
    lines.append("    int32_t  cue;")
    lines.append("    int32_t  target;")
    lines.append("    uint32_t delay;")
    lines.append("} event_data_t;")
    lines.append("")
    lines.append("static const event_data_t s_events[NUM_EVENTS] = {")

    for ev in TASK_SEQUENCE:
        ctx_key = ev["bridge_context_key_id"]
        route_key = ev["bridge_route_key_id"]
        mem_key = ev["bridge_memory_key_id"]
        ctx_val = fp_from_float(ev["bridge_context_value"])
        route_val = fp_from_float(ev["bridge_route_value"])
        mem_val = fp_from_float(ev["bridge_memory_value"])
        cue = fp_from_float(ev["bridge_visible_cue"])
        target = fp_from_float(ev["target"])
        # Use fixed delay = 2 (same as ContinuousEventLoop default)
        delay = 2
        lines.append(
            f"    {{{ev['step']}, {ctx_key}, {route_key}, {mem_key}, "
            f"{ctx_val}, {route_val}, {mem_val}, {cue}, {target}, {delay}}},"
        )

    lines.append("};")
    lines.append("")
    lines.append("#endif /* TEST_FOUR_CORE_48EVENT_DATA_H */")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"Generated {out_path} with {len(TASK_SEQUENCE)} events.")


if __name__ == "__main__":
    main()
